// Code generated by event-spec. DO NOT EDIT.
// Source: checkout_abandoned (v2-0-0)

package analytics

data class CheckoutAbandonedProperties(
    val cartId: String,
)

@Deprecated("Use checkout_started instead.")
suspend fun EventSpec.checkoutAbandoned(props: CheckoutAbandonedProperties, opts: TrackOptions? = null) {
    client.track(
        Event(
            name = "Checkout Abandoned",
            properties = mapOf(
                "cart_id" to props.cartId,
            ),
        ),
        opts,
    )
}
