// Code generated by event-spec. DO NOT EDIT.

package analytics

import io.eventspec.analytics.Client
import io.eventspec.analytics.Event
import io.eventspec.analytics.TrackOptions
import analytics.CheckoutAbandonedProperties
import analytics.WishlistSharedProperties

class EventSpec(internal val client: Client) {

    @Deprecated("Use checkout_started instead.")
    val checkoutAbandoned: suspend (CheckoutAbandonedProperties, TrackOptions?) -> Unit =
        { props, opts -> this.checkoutAbandoned(props, opts) }

    val wishlistShared: suspend (WishlistSharedProperties, TrackOptions?) -> Unit =
        { props, opts -> this.wishlistShared(props, opts) }
}
