// Code generated by event-spec. DO NOT EDIT.
// Source: wishlist_shared (v1-0-0)

package analytics

data class WishlistSharedProperties(
    val wishlistId: String,
)

suspend fun EventSpec.wishlistShared(props: WishlistSharedProperties, opts: TrackOptions? = null) {
    client.track(
        Event(
            name = "Wishlist Shared",
            properties = mapOf(
                "wishlist_id" to props.wishlistId,
            ),
        ),
        opts,
    )
}
