// Code generated by event-spec. DO NOT EDIT.

import { Client, TrackOptions } from '@event-spec/analytics';
export * from './product_viewed';

import { ProductViewedProperties } from './product_viewed';

export class EventSpec {
    constructor(private readonly client: Client) {}

    productViewed(props: ProductViewedProperties, opts?: TrackOptions): Promise<void> {
        return this.client.track({
            name: 'Product Viewed',
            properties: {
                category: props.category,
                product_id: props.productId,
                currency: props.currency,
            },
        }, opts);
    }

    sessionStarted(opts?: TrackOptions): Promise<void> {
        return this.client.track({
            name: 'Session Started',
        }, opts);
    }
}
