// Code generated by event-spec. DO NOT EDIT.

import { Client, TrackOptions } from '@event-spec/api';
export * from './product_viewed';
export * from './session_started';

import { ProductViewedProperties, productViewed } from './product_viewed';
import { sessionStarted } from './session_started';

export class EventSpec {
    constructor(private readonly client: Client) {}

    readonly productViewed = (props: ProductViewedProperties, opts?: TrackOptions) =>
        productViewed(this.client, props, opts);

    readonly sessionStarted = (opts?: TrackOptions) =>
        sessionStarted(this.client, opts);
}
