// Code generated by event-spec. DO NOT EDIT.
// Source: product_viewed (v1-0-0)

export type ProductViewedCategory = "clothing" | "electronics" | "other";

export interface ProductViewedProperties {
    category: ProductViewedCategory;
    productId: string;
    currency?: string;
}
