// Code generated by event-spec. DO NOT EDIT.
// Source: product_viewed (v1-0-0)

import { Client, TrackOptions } from '@dejanradmanovic/event-spec-api';

export type ProductViewedCategory = "clothing" | "electronics" | "other";

export interface ProductViewedProperties {
    category: ProductViewedCategory;
    productId: string;
    currency?: string;
}

export function productViewed(client: Client, props: ProductViewedProperties, opts?: TrackOptions): Promise<void> {
    return client.track({
        name: 'Product Viewed',
        properties: {
            category: props.category,
            product_id: props.productId,
            currency: props.currency,
        },
    }, opts);
}
