// Code generated by event-spec. DO NOT EDIT.
// Source: session_started (v1-0-0)

import { Client, TrackOptions } from '@event-spec/api';

export function sessionStarted(client: Client, opts?: TrackOptions): Promise<void> {
    return client.track({ name: 'Session Started' }, opts);
}
