// Code generated by event-spec. DO NOT EDIT.
// Source: checkout_abandoned (v2-0-0)

import { Client, TrackOptions } from '@dejanradmanovic/event-spec-api';

export interface CheckoutAbandonedProperties {
    cartId: string;
}

/** @deprecated Use checkout_started instead. */
export function checkoutAbandoned(client: Client, props: CheckoutAbandonedProperties, opts?: TrackOptions): Promise<void> {
    return client.track({
        name: 'Checkout Abandoned',
        properties: {
            cart_id: props.cartId,
        },
    }, opts);
}
