// Code generated by event-spec. DO NOT EDIT.

import { Client, TrackOptions } from '@dejanradmanovic/event-spec-api';
export * from './checkout_abandoned';
export * from './wishlist_shared';

import { CheckoutAbandonedProperties, checkoutAbandoned } from './checkout_abandoned';
import { WishlistSharedProperties, wishlistShared } from './wishlist_shared';

export class EventSpec {
    constructor(private readonly client: Client) {}

    /** @deprecated Use checkout_started instead. */
    readonly checkoutAbandoned = (props: CheckoutAbandonedProperties, opts?: TrackOptions) =>
        checkoutAbandoned(this.client, props, opts);

    readonly wishlistShared = (props: WishlistSharedProperties, opts?: TrackOptions) =>
        wishlistShared(this.client, props, opts);
}
