// Code generated by event-spec. DO NOT EDIT.
// Source: wishlist_shared (v1-0-0)

import { Client, TrackOptions } from '@dejanradmanovic/event-spec-api';

export interface WishlistSharedProperties {
    wishlistId: string;
}

export function wishlistShared(client: Client, props: WishlistSharedProperties, opts?: TrackOptions): Promise<void> {
    return client.track({
        name: 'Wishlist Shared',
        properties: {
            wishlist_id: props.wishlistId,
        },
    }, { ...opts, noop: true });
}
