// Code generated by event-spec. DO NOT EDIT.
// Source: checkout_abandoned (v2-0-0)

package analytics

import (
	"context"

	core "github.com/dejanradmanovic/event-spec/analytics"
)

type CheckoutAbandonedProperties struct {
	CartId string
}

// Deprecated: Use checkout_started instead.
func (es *EventSpec) CheckoutAbandoned(ctx context.Context, props CheckoutAbandonedProperties, opts ...core.TrackOption) error {
	return es.client.Track(ctx, core.Event{
		Name: "Checkout Abandoned",
		Properties: map[string]any{
			"cart_id": props.CartId,
		},
	}, opts...)
}
