// Code generated by event-spec. DO NOT EDIT.
// Source: wishlist_shared (v1-0-0)

package analytics

import (
	"context"

	core "github.com/dejanradmanovic/event-spec/analytics"
)

type WishlistSharedProperties struct {
	WishlistId string
}

func (es *EventSpec) WishlistShared(ctx context.Context, props WishlistSharedProperties, opts ...core.TrackOption) error {
	// Draft: dispatches to noop unless the client has WithDraftDispatch(true).
	opts = append([]core.TrackOption{core.WithNoop()}, opts...)
	return es.client.Track(ctx, core.Event{
		Name:   "Wishlist Shared",
		Status: core.EventStatusDraft,
		Properties: map[string]any{
			"wishlist_id": props.WishlistId,
		},
	}, opts...)
}
