// Code generated by event-spec. DO NOT EDIT.
// Source: wishlist_shared (v1-0-0)

package analytics

import (
	"context"

	core "github.com/dejanradmanovic/event-spec/analytics"
)

type WishlistSharedProperties struct {
	WishlistId string
}

func (es *EventSpec) WishlistShared(ctx context.Context, props WishlistSharedProperties, opts ...core.TrackOption) error {
	// Draft: this event is not yet active. Dispatches to noop by default.
	// Remove draft status in the spec to enable real dispatch.
	opts = append([]core.TrackOption{core.WithNoop()}, opts...)
	return es.client.Track(ctx, core.Event{
		Name: "Wishlist Shared",
		Properties: map[string]any{
			"wishlist_id": props.WishlistId,
		},
	}, opts...)
}
