// Code generated by event-spec. DO NOT EDIT.
// Source: product_viewed (v1-0-0)

package analytics

import (
	"context"

	core "github.com/dejanradmanovic/event-spec/analytics"
)

type ProductViewedCategory string

const (
	ProductViewedCategoryClothing    ProductViewedCategory = "clothing"
	ProductViewedCategoryElectronics ProductViewedCategory = "electronics"
	ProductViewedCategoryOther       ProductViewedCategory = "other"
)

type ProductViewedProperties struct {
	Category  ProductViewedCategory
	ProductId string
	Currency  *string
}

func (es *EventSpec) ProductViewed(ctx context.Context, props ProductViewedProperties, opts ...core.TrackOption) error {
	return es.client.Track(ctx, core.Event{
		Name: "Product Viewed",
		Properties: map[string]any{
			"category":   string(props.Category),
			"product_id": props.ProductId,
			"currency":   props.Currency,
		},
	}, opts...)
}
