// Code generated by event-spec. DO NOT EDIT.
// Source: session_started (v1-0-0)

package analytics

import (
	"context"

	core "event-spec/analytics"
)

func (es *EventSpec) SessionStarted(ctx context.Context, opts ...core.TrackOption) error {
	return es.client.Track(ctx, core.Event{
		Name: "Session Started",
	}, opts...)
}
