// Code generated by event-spec. DO NOT EDIT.

package analytics

import io.eventspec.analytics.Client
import io.eventspec.analytics.Event
import io.eventspec.analytics.TrackOptions
import analytics.ProductViewedProperties

class EventSpec(internal val client: Client) {

    val productViewed: suspend (ProductViewedProperties, TrackOptions?) -> Unit =
        { props, opts -> this.productViewed(props, opts) }

    val sessionStarted: suspend (TrackOptions?) -> Unit =
        { opts -> this.sessionStarted(opts) }
}
