// Code generated by event-spec. DO NOT EDIT.
// Source: product_viewed (v1-0-0)

package analytics

enum class ProductViewedCategory(val value: String) {
    CLOTHING("clothing"),
    ELECTRONICS("electronics"),
    OTHER("other"),
}

data class ProductViewedProperties(
    val category: ProductViewedCategory,
    val productId: String,
    val currency: String? = null,
)

suspend fun EventSpec.productViewed(props: ProductViewedProperties, opts: TrackOptions? = null) {
    client.track(
        Event(
            name = "Product Viewed",
            properties = mapOf(
                "category" to props.category.value,
                "product_id" to props.productId,
                "currency" to props.currency,
            ),
        ),
        opts,
    )
}
