// Code generated by event-spec. DO NOT EDIT.
// Source: session_started (v1-0-0)

package analytics

suspend fun EventSpec.sessionStarted(opts: TrackOptions? = null) {
    client.track(
        Event(
            name = "Session Started",
        ),
        opts,
    )
}
